name = "HierarchicalDirichletProcess"
uuid = "0b43e306-a85f-42c8-992d-57462e351534"
authors = ["Ta-Chu Kao <tachu.kao@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
